image: node:18

tasks:
  - init: npm install
    command: npm run dev

ports:
  - port: 5173
    onOpen: open-preview

vscode:
  extensions:
    - bradlc.vscode-tailwindcss
    - esbenp.prettier-vscode

